// Fill in  your WiFi networks SSID and password
#define SECRET_SSID "POWER"
#define SECRET_PASS "yanghwang"

// Fill in the hostname of your AWS IoT broker
#define SECRET_BROKER "a3u94s2b6e05d4-ats.iot.ap-northeast-2.amazonaws.com"

// Fill in the boards public certificate
const char SECRET_CERTIFICATE[] = R"(
-----BEGIN CERTIFICATE-----
MIICiDCCAXCgAwIBAgIUFT8whEzljNHdk5pBdh2/tOOmbocwDQYJKoZIhvcNAQEL
BQAwTTFLMEkGA1UECwxCQW1hem9uIFdlYiBTZXJ2aWNlcyBPPUFtYXpvbi5jb20g
SW5jLiBMPVNlYXR0bGUgU1Q9V2FzaGluZ3RvbiBDPVVTMB4XDTIwMTIxMDExMzIx
M1oXDTQ5MTIzMTIzNTk1OVowGDEWMBQGA1UEAxMNTXlNS1JXaUZpMTAxMDBZMBMG
ByqGSM49AgEGCCqGSM49AwEHA0IABEFe9rDdWbuQz/+BbH+foEFnU/175J4VQcLt
KCrQEEFxHyRwAlA32iEoBvPnS74yPCCh9iaygXsAg97ZKyWITIijYDBeMB8GA1Ud
IwQYMBaAFFLUJYwzsPACHKFvFK/Lgi1BVSB3MB0GA1UdDgQWBBQUxCQXbi/GyfmJ
eoTBeFnCRLehQzAMBgNVHRMBAf8EAjAAMA4GA1UdDwEB/wQEAwIHgDANBgkqhkiG
9w0BAQsFAAOCAQEAdgKIBEz3Ck93/UPEv2yzvDb8WkSABdm4+LycKq/vFbqyN3ZH
wIwsAIOvc1YDlTYTjmBZVI0P6IjJenQLeIfOd476D4XYUaufyLIkHsBhqVkv3IIz
qj/PYNhfnidZ0vJiBj3C5+8MpooYk9VvYazLmCEpoOwS+vwVL8t/vba5z8CL8AUm
mlSNDqHReWc8Z4UAtTt4GLdd6yIjKIitLRDlIdHehGp4wYYgAgm7ZsTF8BIqtCKu
3za8U5m8W7m7zCqibmih9za8H6GgU2oLGjCwBlPGAl5FjgrVU2xYYfXg0u2DjR83
WZD2s4fomlSxTchSV2l4nkfXxP1RutcV+v8kgQ==
-----END CERTIFICATE-----
)";
